/* Writes assets/props/manifest.json — the index js/props.js reads to turn a folder of
   GLBs into a placeable prop library.

   WHY THIS EXISTS AT ALL: a browser cannot list a directory. Over file:// there is no
   index to fetch, and over http you would be trusting the server's autoindex. So
   "drop a glb in a folder and use it" needs a generated manifest, which is what this is.

   Run after adding or removing a prop:
       node tools/build_props_manifest.js

   It reads each GLB's JSON chunk for its real dimensions, so the manifest records the
   authored HEIGHT of every prop — that is the number you want when deciding a `fit`,
   and reading it here beats loading the model in-game to find out. Existing entries in
   the manifest are PRESERVED (your hand-tuned fit/yaw/scale survive a re-run); only new
   files are added and deleted ones dropped.                                          */
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const DIR=path.join(ROOT,'assets','props');
const OUT=path.join(DIR,'manifest.json');

function jsonChunk(p){
 const b=fs.readFileSync(p);
 if(b.length<12||b.readUInt32LE(0)!==0x46546C67)return null;
 let o=12;
 while(o<b.length){const len=b.readUInt32LE(o),t=b.readUInt32LE(o+4);
  if(t===0x4E4F534A)return JSON.parse(b.slice(o+8,o+8+len).toString('utf8'));
  o+=8+len;}
 return null;
}
/* Authored size straight from the accessor MIN/MAX bounds glTF is required to store for
   POSITION — no mesh decode needed. Node transforms are ignored: props are authored at
   origin and `ground`/`fit` normalise on load anyway, so this is a size hint, not a bbox. */
function sizeOf(j){
 if(!j||!j.meshes)return null;
 const a=j.accessors||[];let lo=[1e30,1e30,1e30],hi=[-1e30,-1e30,-1e30],got=false;
 j.meshes.forEach(m=>m.primitives.forEach(p=>{
  const ac=a[p.attributes&&p.attributes.POSITION];
  if(!ac||!ac.min||!ac.max)return;got=true;
  for(let i=0;i<3;i++){lo[i]=Math.min(lo[i],ac.min[i]);hi[i]=Math.max(hi[i],ac.max[i]);}
 }));
 return got?{w:hi[0]-lo[0],h:hi[1]-lo[1],d:hi[2]-lo[2]}:null;
}
if(!fs.existsSync(DIR)){console.error('no assets/props/ folder — create it and add .glb files');process.exit(1);}
let prev={};
try{prev=JSON.parse(fs.readFileSync(OUT,'utf8')).props||{};}catch(e){}

const files=fs.readdirSync(DIR).filter(f=>f.toLowerCase().endsWith('.glb')).sort();
const props={};let added=0,kept=0;
for(const f of files){
 const id=f.replace(/\.glb$/i,'').replace(/[^A-Za-z0-9]+(.)/g,(m,c)=>c.toUpperCase());
 const j=jsonChunk(path.join(DIR,f));
 const sz=sizeOf(j);
 const meshes=j&&j.meshes?j.meshes.length:0;
 const mats=j&&j.materials?j.materials.length:0;
 if(prev[id]){props[id]=Object.assign({},prev[id],{src:f});kept++;}   // keep hand-tuning
 else{props[id]={src:f};added++;}
 props[id].authored=sz?{h:+sz.h.toFixed(3),w:+sz.w.toFixed(3),d:+sz.d.toFixed(3)}:null;
 props[id].parts=meshes;props[id].materials=mats;
 if(!j)console.warn('  ! '+f+' is not a readable glb');
}
const dropped=Object.keys(prev).filter(k=>!props[k]);
fs.writeFileSync(OUT,JSON.stringify({
 note:'generated by tools/build_props_manifest.js — hand edits to fit/scale/yaw are preserved on re-run',
 generated:new Date().toISOString().slice(0,10),
 props
},null,1)+'\n');
console.log('props manifest: '+files.length+' glb ('+added+' new, '+kept+' kept'+
 (dropped.length?', '+dropped.length+' dropped: '+dropped.join(', '):'')+')');
Object.entries(props).forEach(([id,p])=>console.log('  '+id.padEnd(18)+p.src.padEnd(28)+
 (p.authored?('h='+p.authored.h).padEnd(12):'h=?         ')+p.parts+' part(s), '+p.materials+' material(s)'));
console.log('\n-> '+path.relative(ROOT,OUT));
